# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-and-test-express-js:
    docker:
      - image: cimg/node:16.13.0 # latest stable node at the time of writing
    steps:
      - checkout
      - run: echo "this is the build and test express.js job"
      - run: |
          cd back-end
          pwd # for debugging: show current working directory
          ls # for debugging: show sub-directories in here
      - run: |
          cd back-end
          npm ci --legacy-peer-deps # install all dependencies listed in package-lock.json
          npm test # run all unit tests
  build-react-js:
    docker:
      - image: cimg/node:16.13.0 # latest stable node at the time of writing
    steps:
      - checkout
      - run: echo "this is the build react.js job"
      - run: |
          cd front-end
          pwd # for debugging: show current working directory
          ls # for debugging: show sub-directories in here
      - run: |
          cd front-end
          npm ci --legacy-peer-deps # install all dependencies listed in package-lock.json
          npm run build # have react build the stand-alone front-end code

# Orchestrate our job run sequence
workflows:
  build-and-test:
    jobs:
      - build-and-test-express-js
      - build-react-js
