# Define the jobs we want to run for this project
jobs:
  build-react-js:
    docker:
      - image: cimg/node:16.13.0 # latest stable node at the time of writing
    steps:
      - checkout
      - run: echo "this is the build react.js job"
      - run: |
          cd front-end
          pwd # for debugging: show current working directory
          ls # for debugging: show sub-directories in here
      - run: |
          cd front-end
          npm install # install all dependencies listed in package-lock.json
          npm run build # have react build the stand-alone front-end code